/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_josuedejesus;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josue
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregar = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        vin_txt = new javax.swing.JTextField();
        cb_categoria = new javax.swing.JComboBox<>();
        cb_marca = new javax.swing.JComboBox<>();
        cb_carroceria = new javax.swing.JComboBox<>();
        js_puertas = new javax.swing.JSpinner();
        cb_color = new javax.swing.JComboBox<>();
        cb_motor = new javax.swing.JComboBox<>();
        precio_txt = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_hibridacion = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        js_pasajeros = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tiempo_txt = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        butt_guardar = new javax.swing.JButton();
        butt_guardar1 = new javax.swing.JButton();
        jd_listar = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        cb_categoria1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        vin_buscar_txt = new javax.swing.JTextField();
        jd_modificar = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_modificar = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        vin_txt1 = new javax.swing.JTextField();
        cb_categoria2 = new javax.swing.JComboBox<>();
        cb_marca1 = new javax.swing.JComboBox<>();
        cb_carroceria1 = new javax.swing.JComboBox<>();
        js_puertas1 = new javax.swing.JSpinner();
        cb_color1 = new javax.swing.JComboBox<>();
        cb_motor1 = new javax.swing.JComboBox<>();
        precio_txt1 = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cb_hibridacion1 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        js_pasajeros1 = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tiempo_txt1 = new javax.swing.JFormattedTextField();
        jLabel30 = new javax.swing.JLabel();
        butt_guardar2 = new javax.swing.JButton();
        butt_guardar3 = new javax.swing.JButton();
        Refrescar = new javax.swing.JButton();
        jd_eliminar = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        table_eliminar = new javax.swing.JTable();
        Refrescar1 = new javax.swing.JButton();
        Refrescar2 = new javax.swing.JButton();
        Refrescar3 = new javax.swing.JButton();
        butt_agregar = new javax.swing.JButton();
        butt_listar = new javax.swing.JButton();
        butt_modificar = new javax.swing.JButton();
        butt_modificar1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Agregar Vehiculos");

        vin_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vin_txtActionPerformed(evt);
            }
        });

        cb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Generalista", "Premium", "Deportivo" }));
        cb_categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_categoriaMouseClicked(evt);
            }
        });
        cb_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_categoriaActionPerformed(evt);
            }
        });

        cb_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_marcaActionPerformed(evt);
            }
        });

        cb_carroceria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "Familiar", "Hatchback", "Fastback", "SUV" }));

        js_puertas.setModel(new javax.swing.SpinnerNumberModel(2, 2, 4, 2));

        cb_color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Blanco", "Rojo", "Amarillo", "Verde", "Rosado", "Gris", "Azul" }));

        cb_motor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Combustion", "Electrico" }));

        jLabel2.setText("VIN");

        jLabel3.setText("Categoria");

        jLabel4.setText("Marca");

        jLabel5.setText("Carroceria");

        jLabel6.setText("Numero de Puertas");

        jLabel7.setText("Color");

        jLabel8.setText("Motor");

        jLabel9.setText("Precio");

        jLabel10.setText("EUR");

        cb_hibridacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Microhibrido", "Hibrido convencional", "Hibrido enchufable", "Electrico" }));

        jLabel11.setText("Tipo de Hidratacion");

        js_pasajeros.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));

        jLabel12.setText("Cantidad Maxima de Pasajeros");

        jLabel13.setText("Tiempo de Ensamblaje");

        jLabel14.setText("Segundos");

        butt_guardar.setText("Guardar");
        butt_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_guardarMouseClicked(evt);
            }
        });

        butt_guardar1.setText("Regresar");
        butt_guardar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_guardar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butt_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butt_guardar1))
                    .addComponent(js_pasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cb_hibridacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(precio_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addComponent(jLabel10))
                        .addComponent(cb_color, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(vin_txt)
                                .addComponent(cb_categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_marca, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_carroceria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(js_puertas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cb_motor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tiempo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel14)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(cb_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_carroceria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_puertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precio_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_hibridacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_pasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt_guardar)
                    .addComponent(butt_guardar1))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_agregarLayout = new javax.swing.GroupLayout(jd_agregar.getContentPane());
        jd_agregar.getContentPane().setLayout(jd_agregarLayout);
        jd_agregarLayout.setHorizontalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(530, 530, 530)
                        .addComponent(jLabel1))
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jd_agregarLayout.setVerticalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        cb_categoria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Generalista", "Premium", "Deportivo" }));

        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Regresar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1247, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cb_categoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jButton2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_categoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Categoria", jPanel2);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEAT", "Škoda", "Audi", "Volkswagen", "Bentley", "Porsche", "Lamborghini", "Bugatti" }));

        jLabel15.setText("Marca");

        jButton3.setText("Buscar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel16.setText("VIN");

        jButton4.setText("Buscar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(vin_buscar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)))
                        .addGap(0, 781, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)
                            .addComponent(vin_buscar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Marca o VIN", jPanel3);

        javax.swing.GroupLayout jd_listarLayout = new javax.swing.GroupLayout(jd_listar.getContentPane());
        jd_listar.getContentPane().setLayout(jd_listarLayout);
        jd_listarLayout.setHorizontalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jd_listarLayout.setVerticalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel17.setText("Modificar Vehiculo");

        table_modificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_modificarMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_modificar);

        jScrollPane3.setViewportView(jScrollPane4);

        vin_txt1.setEnabled(false);
        vin_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vin_txt1ActionPerformed(evt);
            }
        });

        cb_categoria2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Generalista", "Premium", "Deportivo" }));
        cb_categoria2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_categoria2MouseClicked(evt);
            }
        });
        cb_categoria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_categoria2ActionPerformed(evt);
            }
        });

        cb_carroceria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "Familiar", "Hatchback", "Fastback", "SUV" }));

        js_puertas1.setModel(new javax.swing.SpinnerNumberModel(2, 2, 4, 2));

        cb_color1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Blanco", "Rojo", "Amarillo", "Verde", "Rosado", "Gris", "Azul" }));

        cb_motor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Combustion", "Electrico" }));

        jLabel18.setText("VIN");

        jLabel19.setText("Categoria");

        jLabel20.setText("Marca");

        jLabel21.setText("Carroceria");

        jLabel22.setText("Numero de Puertas");

        jLabel23.setText("Color");

        jLabel24.setText("Motor");

        jLabel25.setText("Precio");

        jLabel26.setText("EUR");

        cb_hibridacion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Microhibrido", "Hibrido convencional", "Hibrido enchufable", "Electrico" }));

        jLabel27.setText("Tipo de Hidratacion");

        js_pasajeros1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));

        jLabel28.setText("Cantidad Maxima de Pasajeros");

        jLabel29.setText("Tiempo de Ensamblaje");

        jLabel30.setText("Segundos");

        butt_guardar2.setText("Actualizar");
        butt_guardar2.setEnabled(false);
        butt_guardar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_guardar2MouseClicked(evt);
            }
        });
        butt_guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_guardar2ActionPerformed(evt);
            }
        });

        butt_guardar3.setText("Regresar");
        butt_guardar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_guardar3MouseClicked(evt);
            }
        });
        butt_guardar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_guardar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(butt_guardar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butt_guardar3))
                    .addComponent(js_pasajeros1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cb_hibridacion1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(precio_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addComponent(jLabel26))
                        .addComponent(cb_color1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(vin_txt1)
                                .addComponent(cb_categoria2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_marca1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_carroceria1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(js_puertas1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cb_motor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tiempo_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel30)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vin_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_categoria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addComponent(cb_marca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_carroceria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_puertas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_color1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_motor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precio_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_hibridacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_pasajeros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempo_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt_guardar2)
                    .addComponent(butt_guardar3))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Refrescar.setText("Refrescar");
        Refrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefrescarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modificarLayout = new javax.swing.GroupLayout(jd_modificar.getContentPane());
        jd_modificar.getContentPane().setLayout(jd_modificarLayout);
        jd_modificarLayout.setHorizontalGroup(
            jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarLayout.createSequentialGroup()
                .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jd_modificarLayout.createSequentialGroup()
                        .addGap(549, 549, 549)
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Refrescar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );
        jd_modificarLayout.setVerticalGroup(
            jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Refrescar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel31.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel31.setText("Eliminar Vehiculo");

        table_eliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_eliminarMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(table_eliminar);

        jScrollPane5.setViewportView(jScrollPane6);

        Refrescar1.setText("Refrescar");
        Refrescar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Refrescar1MouseClicked(evt);
            }
        });

        Refrescar2.setText("Eliminar");
        Refrescar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Refrescar2MouseClicked(evt);
            }
        });

        Refrescar3.setText("Regresar");
        Refrescar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Refrescar3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_eliminarLayout = new javax.swing.GroupLayout(jd_eliminar.getContentPane());
        jd_eliminar.getContentPane().setLayout(jd_eliminarLayout);
        jd_eliminarLayout.setHorizontalGroup(
            jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminarLayout.createSequentialGroup()
                .addGroup(jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_eliminarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(jd_eliminarLayout.createSequentialGroup()
                        .addGroup(jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_eliminarLayout.createSequentialGroup()
                                .addGap(549, 549, 549)
                                .addComponent(jLabel31))
                            .addGroup(jd_eliminarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Refrescar1)))
                        .addGap(0, 553, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jd_eliminarLayout.createSequentialGroup()
                .addGap(554, 554, 554)
                .addComponent(Refrescar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Refrescar3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_eliminarLayout.setVerticalGroup(
            jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_eliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Refrescar1)
                .addGap(29, 29, 29)
                .addGroup(jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Refrescar2)
                    .addComponent(Refrescar3))
                .addContainerGap(491, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butt_agregar.setText("Agregar");
        butt_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_agregarMouseClicked(evt);
            }
        });

        butt_listar.setText("Listar");
        butt_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_listarMouseClicked(evt);
            }
        });
        butt_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_listarActionPerformed(evt);
            }
        });

        butt_modificar.setText("Modificar");
        butt_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_modificarMouseClicked(evt);
            }
        });

        butt_modificar1.setText("Eliminar");
        butt_modificar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_modificar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(butt_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butt_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butt_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butt_modificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butt_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butt_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butt_modificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(410, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vin_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vin_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vin_txtActionPerformed

    private void butt_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_agregarMouseClicked
        // TODO add your handling code here:
        Abrir(jd_agregar);
    }//GEN-LAST:event_butt_agregarMouseClicked

    private void butt_guardar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_guardar1MouseClicked
        // TODO add your handling code here:
        jd_agregar.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_butt_guardar1MouseClicked

    private void cb_categoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_categoriaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_categoriaMouseClicked

    private void cb_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_categoriaActionPerformed
        // TODO add your handling code here:
        if (cb_categoria.getSelectedItem().toString().equals("Generalista")) {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_marca.getModel();
            modelo.removeAllElements();
            modelo.addElement("SEAT");
            modelo.addElement("Škoda");
        }

        if (cb_categoria.getSelectedItem().toString().equals("Premium")) {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_marca.getModel();
            modelo.removeAllElements();
            modelo.addElement("Audi");
            modelo.addElement("Volkswagen");
            modelo.addElement("Bentley");
        }

        if (cb_categoria.getSelectedItem().toString().equals("Deportivo")) {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_marca.getModel();
            modelo.removeAllElements();
            modelo.addElement("Porsche");
            modelo.addElement("Lamborghini");
            modelo.addElement("Bugatti");
        }
    }//GEN-LAST:event_cb_categoriaActionPerformed

    private void butt_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_guardarMouseClicked
        // TODO add your handling code here:
        Dba db = new Dba("./base1.mdb");
        db.conectar();
        try {
            int vin, puertas, pasajeros, ensamblaje, precio;
            String categoria, marca, carroceria, color, motor, hibridacion;
            vin = Integer.parseInt(vin_txt.getText());
            categoria = cb_categoria.getSelectedItem().toString();
            marca = cb_marca.getSelectedItem().toString();
            carroceria = cb_carroceria.getSelectedItem().toString();
            puertas = Integer.parseInt(js_puertas.getValue().toString());
            color = cb_color.getSelectedItem().toString();
            motor = cb_motor.getSelectedItem().toString();
            precio = Integer.parseInt(precio_txt.getText());
            hibridacion = cb_hibridacion.getSelectedItem().toString();
            pasajeros = Integer.parseInt(js_pasajeros.getValue().toString());
            ensamblaje = Integer.parseInt(tiempo_txt.getText());
            db.query.execute("select vin from vehiculos");
            ResultSet resultado = db.query.getResultSet();
            db.query.execute("Insert into vehiculos" + "(vin, categoria, marca, carroceria, puertas, color, motor, precio, hibridacion, pasajeros, ensamblaje)"
                    + " VALUES ('" + vin + "', '" + categoria + "','" + marca + "', '" + carroceria + "', '" + puertas + "', '" + color + "', '" + motor + "', '" + precio + "', '" + hibridacion + "', '" + pasajeros + "', '" + ensamblaje + "')");
            db.commit();
            JOptionPane.showMessageDialog(this, "Datos guardados exitosamente!");

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_butt_guardarMouseClicked

    private void butt_listarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_listarMouseClicked
        // TODO add your handling code here:
        Abrir(jd_listar);
    }//GEN-LAST:event_butt_listarMouseClicked

    private void butt_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_listarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_listarActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Dba db = new Dba("./base1.mdb");
        db.conectar();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{"vin", "categoria", "marca", "carroceria", "color", "motor", "precio"}));
        DefaultTableModel datos = (DefaultTableModel) jTable1.getModel();

        try {
            if (cb_categoria1.getSelectedItem().toString().equals("Generalista")) {
                db.query.execute("select vin, categoria, marca, carroceria, color, motor, precio from vehiculos where categoria = 'Generalista'");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    Object tabla[] = {rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getInt(7)};
                    datos.addRow(tabla);
                }
            }

            if (cb_categoria1.getSelectedItem().toString().equals("Premium")) {
                db.query.execute("select vin, categoria, marca, carroceria, color, motor, precio from vehiculos where categoria = 'Premium'");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    Object tabla[] = {rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getInt(7)};
                    datos.addRow(tabla);
                }
            }

            if (cb_categoria1.getSelectedItem().toString().equals("Deportivo")) {
                db.query.execute("select vin, categoria, marca, carroceria, color, motor, precio from vehiculos where categoria = 'Deportivo'");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    Object tabla[] = {rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getInt(7)};
                    datos.addRow(tabla);
                }
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jd_listar.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Dba db = new Dba("./base1.mdb");
        db.conectar();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{"vin", "categoria", "marca", "carroceria", "color", "motor", "precio"}));
        DefaultTableModel datos = (DefaultTableModel) jTable1.getModel();
        String marca = jComboBox1.getSelectedItem().toString();
        try {
            db.query.execute("select vin, categoria, marca, carroceria, color, motor, precio from vehiculos where marca = "+marca+"");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {
                Object tabla[] = {rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getInt(7)};
                datos.addRow(tabla);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        Dba db = new Dba("./base1.mdb");
        db.conectar();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{"vin", "categoria", "marca", "carroceria", "color", "motor", "precio"}));
        DefaultTableModel datos = (DefaultTableModel) jTable1.getModel();
        int vin = Integer.parseInt(vin_buscar_txt.getText());
        try {
            db.query.execute("select vin, categoria, marca, carroceria, color, motor, precio from vehiculos where vin = "+vin+"");
            ResultSet rs = db.query.getResultSet();
            while (rs.next()) {
                Object tabla[] = {rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getInt(7)};
                datos.addRow(tabla);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void vin_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vin_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vin_txt1ActionPerformed

    private void cb_categoria2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_categoria2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb_categoria2MouseClicked

    private void cb_categoria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_categoria2ActionPerformed
        // TODO add your handling code here:
        if (cb_categoria2.getSelectedItem().toString().equals("Generalista")) {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_marca1.getModel();
            modelo.removeAllElements();
            modelo.addElement("SEAT");
            modelo.addElement("Škoda");
        }

        if (cb_categoria2.getSelectedItem().toString().equals("Premium")) {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_marca1.getModel();
            modelo.removeAllElements();
            modelo.addElement("Audi");
            modelo.addElement("Volkswagen");
            modelo.addElement("Bentley");
        }

        if (cb_categoria2.getSelectedItem().toString().equals("Deportivo")) {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_marca1.getModel();
            modelo.removeAllElements();
            modelo.addElement("Porsche");
            modelo.addElement("Lamborghini");
            modelo.addElement("Bugatti");
        }
    }//GEN-LAST:event_cb_categoria2ActionPerformed

    private void butt_guardar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_guardar2MouseClicked
        // TODO add your handling code here:
        int index = -1;
        Dba db = new Dba("./base1.mdb");
        db.conectar();
        //index = tabla_maestros.getSelectedRow();
        try {
            if (table_modificar.getSelectedRow() >= 0) {
                
            butt_guardar2.setEnabled(true);
            DefaultTableModel modelo = (DefaultTableModel) table_modificar.getModel();
            int vin = Integer.parseInt(modelo.getValueAt((table_modificar.getSelectedRow()), 0).toString());
            vin_txt1.setText(modelo.getValueAt(table_modificar.getSelectedRow(), 0).toString());
            String categoria = modelo.getValueAt(table_modificar.getSelectedRow(), 1).toString();
            String marca = modelo.getValueAt(table_modificar.getSelectedRow(), 2).toString();
            String carroceria = modelo.getValueAt(table_modificar.getSelectedRow(), 3).toString();
            int puertas = Integer.parseInt(modelo.getValueAt(table_modificar.getSelectedRow(), 4).toString());
            String color = modelo.getValueAt(table_modificar.getSelectedRow(), 5).toString();
            String motor = modelo.getValueAt(table_modificar.getSelectedRow(), 6).toString();
            precio_txt1.setText(modelo.getValueAt(table_modificar.getSelectedRow(), 7).toString());
            String hidratacion = modelo.getValueAt(table_modificar.getSelectedRow(), 8).toString();
            int pasajeros = Integer.parseInt(modelo.getValueAt(table_modificar.getSelectedRow(), 9).toString());
            tiempo_txt1.setText(modelo.getValueAt(table_modificar.getSelectedRow(), 10).toString());
            cb_categoria2.setSelectedItem(categoria);
            cb_color1.setSelectedItem(color);
            cb_motor1.setSelectedItem(motor);
           cb_marca1.setSelectedItem(marca);
            cb_carroceria1.setSelectedItem(carroceria);
            js_puertas1.setValue(puertas);
             cb_hibridacion1.setSelectedItem(hidratacion);
            js_pasajeros1.setValue(pasajeros);
            db.query.execute("update vehiculos categoria ="+categoria+" where vin ="+vin+"");
            db.query.execute("update vehiculos marca ="+marca+" where vin = "+vin+"");
            db.query.execute("update vehiculos carroceria ="+carroceria+" where vin ="+vin+"");
            db.commit();
            refrescarTabla(table_modificar);
            JOptionPane.showMessageDialog(this, "Se actualizaron los datos exitosamente!");
            butt_guardar2.setEnabled(false);
        }
            
        } catch (SQLException ex) {
            ex.getStackTrace();
        }
    }//GEN-LAST:event_butt_guardar2MouseClicked

    private void butt_guardar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_guardar3MouseClicked
        // TODO add your handling code here:
        jd_modificar.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_butt_guardar3MouseClicked

    private void butt_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_modificarMouseClicked
        // TODO add your handling code here:
        Abrir(jd_modificar);
        refrescarTabla(table_modificar);
    }//GEN-LAST:event_butt_modificarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RefrescarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefrescarMouseClicked
        // TODO add your handling code here:
        Dba db = new Dba("./base1.mdb");
        db.conectar();
        
        table_modificar.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{"vin", "categoria", "marca", "carroceria", "puertas","color", "motor", "precio", "hibridacion", "pasajeros", "ensamblaje"}));
        DefaultTableModel datos = (DefaultTableModel) table_modificar.getModel();
        
        try{
        db.query.execute("select vin, categoria, marca, carroceria, puertas, color, motor, precio, hibridacion, pasajeros, ensamblaje from vehiculos");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    Object tabla[] = {rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getInt(5), rs.getString(6), rs.getString(7), rs.getInt(8), rs.getString(9),rs.getInt(10), rs.getInt(11)};
                    datos.addRow(tabla);
                }
        }catch(SQLException ex)
        {
            ex.printStackTrace();
        }
        db.desconectar();
    }//GEN-LAST:event_RefrescarMouseClicked

    private void table_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_modificarMouseClicked
        // TODO add your handling code here:
        if (table_modificar.getSelectedRow() >= 0) {
            butt_guardar2.setEnabled(true);
            DefaultTableModel modelo = (DefaultTableModel) table_modificar.getModel();
            vin_txt1.setText(modelo.getValueAt(table_modificar.getSelectedRow(), 0).toString());
            String categoria = modelo.getValueAt(table_modificar.getSelectedRow(), 1).toString();
            String marca = modelo.getValueAt(table_modificar.getSelectedRow(), 2).toString();
            String carroceria = modelo.getValueAt(table_modificar.getSelectedRow(), 3).toString();
            int puertas = Integer.parseInt(modelo.getValueAt(table_modificar.getSelectedRow(), 4).toString());
            String color = modelo.getValueAt(table_modificar.getSelectedRow(), 5).toString();
            String motor = modelo.getValueAt(table_modificar.getSelectedRow(), 6).toString();
            precio_txt1.setText(modelo.getValueAt(table_modificar.getSelectedRow(), 7).toString());
            String hidratacion = modelo.getValueAt(table_modificar.getSelectedRow(), 8).toString();
            int pasajeros = Integer.parseInt(modelo.getValueAt(table_modificar.getSelectedRow(), 9).toString());
            tiempo_txt1.setText(modelo.getValueAt(table_modificar.getSelectedRow(), 10).toString());
            cb_categoria2.setSelectedItem(categoria);
            cb_color1.setSelectedItem(color);
            cb_motor1.setSelectedItem(motor);
           cb_marca1.setSelectedItem(marca);
            cb_carroceria1.setSelectedItem(carroceria);
            js_puertas1.setValue(puertas);
             cb_hibridacion1.setSelectedItem(hidratacion);
            js_pasajeros1.setValue(pasajeros);
        }
    }//GEN-LAST:event_table_modificarMouseClicked

    private void cb_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_marcaActionPerformed

    private void butt_guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_guardar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_guardar2ActionPerformed

    private void butt_guardar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_guardar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_guardar3ActionPerformed

    private void Refrescar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Refrescar1MouseClicked
        // TODO add your handling code here:
        refrescarTabla(table_eliminar);
    }//GEN-LAST:event_Refrescar1MouseClicked

    private void table_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_eliminarMouseClicked
        // TODO add your handling code here:
        Dba db = new Dba("./base1.mdb");
        db.conectar();
        if (table_eliminar.getSelectedRow() >= 0) {
            butt_guardar2.setEnabled(true);
            DefaultTableModel modelo = (DefaultTableModel) table_eliminar.getModel();
            int vin = Integer.parseInt(modelo.getValueAt(table_eliminar.getSelectedRow(), 0).toString());
            try
            {
                db.query.execute("delete from vehiculos where vin ="+vin+"");
                db.commit();
            }catch(SQLException ex)
            {
                ex.printStackTrace();
            }
            db.desconectar();
        }
    }//GEN-LAST:event_table_eliminarMouseClicked

    private void Refrescar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Refrescar2MouseClicked
        // TODO add your handling code here:
        refrescarTabla(table_eliminar);
        JOptionPane.showMessageDialog(this, "Vehiculo ha sido eliminado exitosamente!");
    }//GEN-LAST:event_Refrescar2MouseClicked

    private void butt_modificar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_modificar1MouseClicked
        // TODO add your handling code here:
        Abrir(jd_eliminar);
        refrescarTabla(table_modificar);
    }//GEN-LAST:event_butt_modificar1MouseClicked

    private void Refrescar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Refrescar3MouseClicked
        // TODO add your handling code here:
        jd_eliminar.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_Refrescar3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    private void Abrir(JDialog opcion) {
        this.setVisible(false);
        opcion.setModal(true);
        opcion.pack();
        opcion.setLocationRelativeTo(this);
        opcion.setVisible(true);
    }
    
    private void refrescarTabla(JTable table)
    {
        Dba db = new Dba("./base1.mdb");
        db.conectar();
        
        table.setModel(new javax.swing.table.DefaultTableModel(new Object[][]{}, new String[]{"vin", "categoria", "marca", "carroceria", "puertas","color", "motor", "precio", "hibridacion", "pasajeros", "ensamblaje"}));
        DefaultTableModel datos = (DefaultTableModel) table.getModel();
        
        try{
        db.query.execute("select vin, categoria, marca, carroceria, puertas, color, motor, precio, hibridacion, pasajeros, ensamblaje from vehiculos");
                ResultSet rs = db.query.getResultSet();
                while (rs.next()) {
                    Object tabla[] = {rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getInt(5), rs.getString(6), rs.getString(7), rs.getInt(8), rs.getString(9),rs.getInt(10), rs.getInt(11)};
                    datos.addRow(tabla);
                }
        }catch(SQLException ex)
        {
            ex.printStackTrace();
        }
        db.desconectar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Refrescar;
    private javax.swing.JButton Refrescar1;
    private javax.swing.JButton Refrescar2;
    private javax.swing.JButton Refrescar3;
    private javax.swing.JButton butt_agregar;
    private javax.swing.JButton butt_guardar;
    private javax.swing.JButton butt_guardar1;
    private javax.swing.JButton butt_guardar2;
    private javax.swing.JButton butt_guardar3;
    private javax.swing.JButton butt_listar;
    private javax.swing.JButton butt_modificar;
    private javax.swing.JButton butt_modificar1;
    private javax.swing.JComboBox<String> cb_carroceria;
    private javax.swing.JComboBox<String> cb_carroceria1;
    private javax.swing.JComboBox<String> cb_categoria;
    private javax.swing.JComboBox<String> cb_categoria1;
    private javax.swing.JComboBox<String> cb_categoria2;
    private javax.swing.JComboBox<String> cb_color;
    private javax.swing.JComboBox<String> cb_color1;
    private javax.swing.JComboBox<String> cb_hibridacion;
    private javax.swing.JComboBox<String> cb_hibridacion1;
    private javax.swing.JComboBox<String> cb_marca;
    private javax.swing.JComboBox<String> cb_marca1;
    private javax.swing.JComboBox<String> cb_motor;
    private javax.swing.JComboBox<String> cb_motor1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JDialog jd_agregar;
    private javax.swing.JDialog jd_eliminar;
    private javax.swing.JDialog jd_listar;
    private javax.swing.JDialog jd_modificar;
    private javax.swing.JSpinner js_pasajeros;
    private javax.swing.JSpinner js_pasajeros1;
    private javax.swing.JSpinner js_puertas;
    private javax.swing.JSpinner js_puertas1;
    private javax.swing.JFormattedTextField precio_txt;
    private javax.swing.JFormattedTextField precio_txt1;
    private javax.swing.JTable table_eliminar;
    private javax.swing.JTable table_modificar;
    private javax.swing.JFormattedTextField tiempo_txt;
    private javax.swing.JFormattedTextField tiempo_txt1;
    private javax.swing.JTextField vin_buscar_txt;
    private javax.swing.JTextField vin_txt;
    private javax.swing.JTextField vin_txt1;
    // End of variables declaration//GEN-END:variables
}
